languageCode = "en-gb"
baseUrl = "https://nostalgic-snyder-66983c.netlify.com/"
title = "Vegan Dave"
theme = "oakley"
[taxonomies]
  tag = "tags"

[permalinks]
  page = ":filename"

[menu]
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"

[[menu.main]]
  identifier = "recipe"
  name = "Recipes"
  url = "/recipe/"

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/post/"