baseURL = "http://example.org/"
languageCode = "en-gb"
title = "Vegan Dave"
theme = "VeganDave"
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
  page = ":filename"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "recipe"
    name = "Recipes"
    url = "/recipe/"

    [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/post/"