baseURL = "https://markallum.github.io/VeganDave/"
publishDir = "docs"
languageCode = "en-gb"
title = "Vegan Dave"
theme = "VeganDave"

[permalinks]
  page = ":filename"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "about/"

  [[menu.main]]
    identifier = "recipe"
    name = "Recipes"
    url = "recipe/"

    [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "post/"